### ISSUE TITLE
feat : Live Activity 미러링 

### ISSUE THREAD

**Issue by chamroro** [BostonGosari/Outline#263]
## ✏️ Summary
Live Activity 미러링 

<br>

## ✨ Description
러닝중인 세션 상태를 나타냅니다. 

<br>

## ✓ Todo
- [ ] UI 구현
- [ ] 미러링
<br>

## 🗒️ Note (optional)
타일러가 Workout session 완료하시기 전까진 일단 UI 를 그려보겠습니다 !!

**Comment by hyunjuntyler** [comment]
Live Activity 라니 벌써 두근되는군요
